"""
Generates src/basemap-catalog.js from the Python basemap registry.

The JS model's addBasemap resolves names against a catalogue; Python's resolves
through xyzservices plus the registry (swiftmap/basemap_registry.py). One
source: this script runs the SAME resolution add_basemap uses for a curated
provider list and writes the finished entries -- url, attribution, zoom
ceilings, subdomains -- into a generated JS module, so the two sides cannot
disagree about a tile URL. A network that swaps its registry file reruns this
(`python scripts/generate_basemap_catalog.py`) and commits the result;
`npm run build` does not regenerate it, since building JS must not need Python.

Curated deliberately: xyzservices catalogues 878 providers and shipping them
all would bloat every bundle for names nobody calls. The list below is the
defaults plus the providers the docs and examples reach for; extend it here
when another earns its place.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from swiftmap import basemap_registry as reg  # noqa: E402

# The dozen earning their bundle bytes: the seeded defaults' providers first.
XYZ_PROVIDERS = [
    "OpenStreetMap.Mapnik",
    "CartoDB.DarkMatter",
    "CartoDB.DarkMatterNoLabels",
    "CartoDB.Positron",
    "CartoDB.PositronNoLabels",
    "CartoDB.Voyager",
    "Esri.WorldImagery",
    "Esri.WorldStreetMap",
    "Esri.WorldTopoMap",
    "Esri.WorldGrayCanvas",
    "Esri.NatGeoWorldMap",
    "OpenTopoMap",
]

# xyzservices.query_name's tolerance: lowercase, with ". -_/" removed -- the
# rule that lets "CartoDB DarkMatter" and "cartodb darkmatter" both resolve.
_STRIP = str.maketrans({c: "" for c in ". -_/"})


def query_key(name: str) -> str:
    return name.lower().translate(_STRIP)


def xyz_entry(canonical: str) -> dict:
    provider = reg.SERVICES.query_name(canonical)
    url = provider.build_url(fill_subdomain=False)
    max_native_zoom = provider.get("max_zoom", 19)
    entry = {
        "name": canonical,
        "url": url,
        "attribution": provider.get("html_attribution") or provider.get("attribution", ""),
        "max_zoom": max(22, max_native_zoom),
        "max_native_zoom": max_native_zoom,
    }
    if provider.get("subdomains"):
        entry["subdomains"] = provider["subdomains"]
    return entry


def main():
    xyz = {}
    for canonical in XYZ_PROVIDERS:
        xyz[query_key(canonical)] = xyz_entry(canonical)

    aliases = {name: target for name, target in reg.ALIASES.items()
               if query_key(target) in xyz}

    presets = {}
    for name, info in reg.BASEMAPS.items():
        presets[name] = {
            "name": name,
            "url": info["url"],
            "attribution": info.get("attribution", ""),
            "max_zoom": info.get("max_zoom", 22),
            "max_native_zoom": info.get("max_native_zoom", 19),
        }

    wms = {}
    for category in reg.WMS_PROVIDERS.values():
        for key, entry in category.items():
            record = {
                "name": entry.get("name", key),
                "url": entry["url"],
                "attribution": entry.get("attribution", ""),
                "max_zoom": entry.get("max_zoom", 22),
                "layers": entry["layers"],
                "format": entry.get("format", "image/png"),
                "version": entry.get("version", "1.1.1"),
                "transparent": entry.get("transparent", False),
            }
            if "max_native_zoom" in entry:
                record["max_native_zoom"] = entry["max_native_zoom"]
            if entry.get("styles"):
                record["styles"] = entry["styles"]
            wms[key.lower()] = record
            for alias in entry.get("aliases", []):
                wms[alias.lower()] = record

    defaults = reg.DEFAULT_BASEMAPS

    body = f"""// GENERATED by scripts/generate_basemap_catalog.py -- do not edit.
//
// The finished entries add_basemap resolves names to, produced by the SAME
// Python resolution (the registry plus xyzservices) the server side uses, so a
// tile URL cannot differ between stacks. A network that swaps its registry
// file reruns the generator and commits the result. Curated, not the whole
// xyzservices catalogue: {len(XYZ_PROVIDERS)} providers, the presets, the WMS
// registry and the per-CRS defaults a bare map seeds from.
export const XYZ = {json.dumps(xyz, indent=1, sort_keys=True)};

// Historical spellings, forwarded exactly as Python's ALIASES are.
export const ALIASES = {json.dumps(aliases, indent=1, sort_keys=True)};

// Hand-defined tiles the catalogue cannot supply (the EPSG:4326 imagery).
export const PRESETS = {json.dumps(presets, indent=1, sort_keys=True)};

// WMS services by lowercased name and alias.
export const WMS = {json.dumps(wms, indent=1, sort_keys=True)};

// What a bare map seeds, per CRS: [name, initially_visible] pairs resolved
// through addBasemap. A CRS with no row falls back to EPSG:3857's.
export const DEFAULT_BASEMAPS = {json.dumps(defaults, indent=1, sort_keys=True)};

// xyzservices.query_name's tolerance: lowercase with ". -_/" removed.
export const queryKey = (name) => String(name).toLowerCase().replace(/[. \\-_/]/g, "");
"""
    out = Path(__file__).resolve().parent.parent / "src" / "basemap-catalog.js"
    out.write_text(body, encoding="utf-8")
    print(f"wrote {out} ({len(xyz)} xyz, {len(presets)} presets, {len(wms)} wms keys)")


if __name__ == "__main__":
    main()
