"""
Builds swiftmap/static/widget.js from src/, using only the Python standard library.

`npm run build` (build.mjs, esbuild) is the canonical builder and produces a better
artifact -- an inline sourcemap for debugging, and real ES module scoping instead of one
shared scope. Use it whenever Node is available.

This exists for environments where it is not: an isolated network where the source can
be brought across but node_modules cannot, and where the built bundle is too large to
transcribe by hand. It is deliberately dependency-free so it runs anywhere Python does.

What makes this possible is that src/ imports nothing from npm. Leaflet and Leaflet.glify
are fetched at runtime by loadJS/loadCSS, so the bundle is only swiftmap's own modules and
flattening them is a matter of ordering, not resolution.

Flattening is only safe while no two modules declare the same top-level name, since they
all end up in one scope. That is checked on every run and the build fails loudly rather
than silently shadowing a function -- which is the failure this approach invites, and the
reason esbuild replaced the older concatenating loader.

    python tools/bundle.py            # writes swiftmap/static/
    python tools/bundle.py --check    # is a bundle this script wrote still current?

The two builders do not produce identical bytes, so --check only judges a bundle this
script wrote; against an esbuild build it says so and passes.
"""
import re
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
OUT_DIR = ROOT / "swiftmap" / "static"
ENTRY = "anywidget.js"
MARKER = "Generated by tools/bundle.py"

# `import ... from "./x.js";` and the side-effect form `import "./x.js";`
IMPORT_RE = re.compile(r'^\s*import\s+(?:.*?\s+from\s+)?["\'](\.[^"\']+)["\'];?\s*$', re.M)
# `export { a, b };` and `export { a } from "./x.js";` -- the named surface is rebuilt by
# flattening, so these lines carry no meaning once everything shares a scope.
EXPORT_LIST_RE = re.compile(r'^\s*export\s*\{[^}]*\}\s*(?:from\s*["\'][^"\']+["\'])?;?\s*$', re.M)
# The `export` keyword in front of a declaration. `export default` is left alone.
EXPORT_KEYWORD_RE = re.compile(r'^export\s+(?=(?:async\s+)?(?:function|const|let|var|class)\s)', re.M)
DECL_RE = re.compile(r'^(?:async\s+)?(?:function|const|let|var|class)\s+([A-Za-z_$][\w$]*)', re.M)


def resolve(spec, importer):
    """Resolves a relative specifier against the importing file."""
    target = (importer.parent / spec).resolve()
    if not target.exists() and not target.suffix:
        target = target.with_suffix(".js")
    if not target.exists():
        raise SystemExit(f"error: {importer.name} imports {spec!r}, which does not exist")
    return target


def collect(entry):
    """Returns modules in dependency order: a file appears after everything it imports."""
    order, seen, visiting = [], set(), set()

    def visit(path):
        if path in seen:
            return
        if path in visiting:
            raise SystemExit(f"error: circular import involving {path.name}")
        visiting.add(path)
        source = path.read_text(encoding="utf-8")
        for spec in IMPORT_RE.findall(source):
            visit(resolve(spec, path))
        visiting.discard(path)
        seen.add(path)
        order.append(path)

    visit(entry)
    return order


def strip(source):
    """Removes the module syntax that flattening makes meaningless."""
    source = IMPORT_RE.sub("", source)
    source = EXPORT_LIST_RE.sub("", source)
    source = EXPORT_KEYWORD_RE.sub("", source)
    return source.strip()


def check_collisions(modules):
    """
    Rejects a build where two modules declare the same top-level name.

    Flattening puts every module in one scope, so a duplicate silently shadows rather than
    erroring at runtime -- the map would render with one function quietly replaced by
    another. esbuild renames around this; here it has to be a hard failure.
    """
    owners = {}
    clashes = []
    for path in modules:
        for name in DECL_RE.findall(strip(path.read_text(encoding="utf-8"))):
            if name in owners and owners[name] != path.name:
                clashes.append(f"  {name!r} declared in both {owners[name]} and {path.name}")
            owners[name] = path.name
    if clashes:
        raise SystemExit(
            "error: top-level name collisions prevent flattening:\n" + "\n".join(clashes) +
            "\n\nRename one of each pair, or build with `npm run build` instead."
        )


def build():
    modules = collect(SRC / ENTRY)
    check_collisions(modules)

    parts = [
        f"// {MARKER} -- do not edit.",
        "// Flattened from src/ without esbuild. See tools/bundle.py for why this exists.",
        "",
    ]
    defaults = 0
    for path in modules:
        body = strip(path.read_text(encoding="utf-8"))
        defaults += len(re.findall(r'^export\s+default\b', body, re.M))
        parts += [f"// ---- src/{path.name} " + "-" * (60 - len(path.name)), body, ""]

    if defaults != 1:
        raise SystemExit(f"error: expected exactly one `export default`, found {defaults}. "
                         f"anywidget loads the default export, so the bundle needs one.")

    return "\n".join(parts) + "\n", modules


def main():
    bundle, modules = build()
    css = (SRC / "map.css").read_text(encoding="utf-8")
    js_out, css_out = OUT_DIR / "widget.js", OUT_DIR / "widget.css"

    if "--check" in sys.argv:
        # The two builders do not produce identical bytes, so a plain comparison would
        # call an esbuild-built bundle stale forever. Only a bundle this script wrote is
        # its to judge; anything else is reported as not ours and left alone.
        if not js_out.exists():
            print(f"missing: {js_out.relative_to(ROOT)} -- run `python tools/bundle.py`")
            return 1
        if MARKER not in js_out.read_text(encoding="utf-8"):
            print(f"{js_out.relative_to(ROOT)} was built by esbuild, not this script; "
                  f"check it with `npm run build` instead")
            return 0

        stale = [p.name for p, cur in ((js_out, bundle), (css_out, css))
                 if not p.exists() or p.read_text(encoding="utf-8") != cur]
        if stale:
            print(f"stale: {', '.join(stale)} -- run `python tools/bundle.py`")
            return 1
        print("swiftmap/static/ is current")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    js_out.write_text(bundle, encoding="utf-8", newline="\n")
    css_out.write_text(css, encoding="utf-8", newline="\n")
    print(f"wrote {js_out.relative_to(ROOT)} ({len(bundle) / 1024:.0f} KB) "
          f"from {len(modules)} modules: {', '.join(p.name for p in modules)}")
    print(f"wrote {css_out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
