// GENERATED by scripts/generate_basemap_catalog.py -- do not edit.
//
// The finished entries add_basemap resolves names to, produced by the SAME
// Python resolution (the registry plus xyzservices) the server side uses, so a
// tile URL cannot differ between stacks. A network that swaps its registry
// file reruns the generator and commits the result. Curated, not the whole
// xyzservices catalogue: 12 providers, the presets, the WMS
// registry and the per-CRS defaults a bare map seeds from.
export const XYZ = {
 "cartodbdarkmatter": {
  "attribution": "&copy; <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors &copy; <a href=\"https://carto.com/attributions\">CARTO</a>",
  "max_native_zoom": 20,
  "max_zoom": 22,
  "name": "CartoDB.DarkMatter",
  "subdomains": "abcd",
  "url": "https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png"
 },
 "cartodbdarkmatternolabels": {
  "attribution": "&copy; <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors &copy; <a href=\"https://carto.com/attributions\">CARTO</a>",
  "max_native_zoom": 20,
  "max_zoom": 22,
  "name": "CartoDB.DarkMatterNoLabels",
  "subdomains": "abcd",
  "url": "https://{s}.basemaps.cartocdn.com/dark_nolabels/{z}/{x}/{y}.png"
 },
 "cartodbpositron": {
  "attribution": "&copy; <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors &copy; <a href=\"https://carto.com/attributions\">CARTO</a>",
  "max_native_zoom": 20,
  "max_zoom": 22,
  "name": "CartoDB.Positron",
  "subdomains": "abcd",
  "url": "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png"
 },
 "cartodbpositronnolabels": {
  "attribution": "&copy; <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors &copy; <a href=\"https://carto.com/attributions\">CARTO</a>",
  "max_native_zoom": 20,
  "max_zoom": 22,
  "name": "CartoDB.PositronNoLabels",
  "subdomains": "abcd",
  "url": "https://{s}.basemaps.cartocdn.com/light_nolabels/{z}/{x}/{y}.png"
 },
 "cartodbvoyager": {
  "attribution": "&copy; <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors &copy; <a href=\"https://carto.com/attributions\">CARTO</a>",
  "max_native_zoom": 20,
  "max_zoom": 22,
  "name": "CartoDB.Voyager",
  "subdomains": "abcd",
  "url": "https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}.png"
 },
 "esrinatgeoworldmap": {
  "attribution": "Tiles &copy; Esri &mdash; National Geographic, Esri, DeLorme, NAVTEQ, UNEP-WCMC, USGS, NASA, ESA, METI, NRCAN, GEBCO, NOAA, iPC",
  "max_native_zoom": 16,
  "max_zoom": 22,
  "name": "Esri.NatGeoWorldMap",
  "url": "https://server.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer/tile/{z}/{y}/{x}"
 },
 "esriworldgraycanvas": {
  "attribution": "Tiles &copy; Esri &mdash; Esri, DeLorme, NAVTEQ",
  "max_native_zoom": 16,
  "max_zoom": 22,
  "name": "Esri.WorldGrayCanvas",
  "url": "https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}"
 },
 "esriworldimagery": {
  "attribution": "Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community",
  "max_native_zoom": 19,
  "max_zoom": 22,
  "name": "Esri.WorldImagery",
  "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
 },
 "esriworldstreetmap": {
  "attribution": "Tiles &copy; Esri &mdash; Source: Esri, DeLorme, NAVTEQ, USGS, Intermap, iPC, NRCAN, Esri Japan, METI, Esri China (Hong Kong), Esri (Thailand), TomTom, 2012",
  "max_native_zoom": 19,
  "max_zoom": 22,
  "name": "Esri.WorldStreetMap",
  "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"
 },
 "esriworldtopomap": {
  "attribution": "Tiles &copy; Esri &mdash; Esri, DeLorme, NAVTEQ, TomTom, Intermap, iPC, USGS, FAO, NPS, NRCAN, GeoBase, Kadaster NL, Ordnance Survey, Esri Japan, METI, Esri China (Hong Kong), and the GIS User Community",
  "max_native_zoom": 19,
  "max_zoom": 22,
  "name": "Esri.WorldTopoMap",
  "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"
 },
 "openstreetmapmapnik": {
  "attribution": "&copy; <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors",
  "max_native_zoom": 19,
  "max_zoom": 22,
  "name": "OpenStreetMap.Mapnik",
  "url": "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
 },
 "opentopomap": {
  "attribution": "Map data: &copy; <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors, <a href=\"http://viewfinderpanoramas.org\">SRTM</a> | Map style: &copy; <a href=\"https://opentopomap.org\">OpenTopoMap</a> (<a href=\"https://creativecommons.org/licenses/by-sa/3.0/\">CC-BY-SA</a>)",
  "max_native_zoom": 17,
  "max_zoom": 22,
  "name": "OpenTopoMap",
  "url": "https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png"
 }
};

// Historical spellings, forwarded exactly as Python's ALIASES are.
export const ALIASES = {
 "CartoDB dark_matter": "CartoDB.DarkMatter",
 "CartoDB positron": "CartoDB.Positron",
 "Dark Matter": "CartoDB.DarkMatter",
 "DarkMatter": "CartoDB.DarkMatter",
 "Open Street Map": "OpenStreetMap.Mapnik",
 "OpenStreetMap": "OpenStreetMap.Mapnik",
 "Positron": "CartoDB.Positron"
};

// Hand-defined tiles the catalogue cannot supply (the EPSG:4326 imagery).
export const PRESETS = {
 "Esri WGS84": {
  "attribution": "Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community",
  "max_native_zoom": 15,
  "max_zoom": 15,
  "name": "Esri WGS84",
  "url": "https://wi.maptiles.arcgis.com/arcgis/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
 }
};

// WMS services by lowercased name and alias.
export const WMS = {
 "usgs imagery": {
  "attribution": "USGS The National Map",
  "format": "image/png",
  "layers": "0",
  "max_zoom": 22,
  "name": "USGS Imagery",
  "transparent": false,
  "url": "https://basemap.nationalmap.gov/arcgis/services/USGSImageryOnly/MapServer/WmsServer",
  "version": "1.1.1"
 },
 "usgs imagery wms": {
  "attribution": "USGS The National Map",
  "format": "image/png",
  "layers": "0",
  "max_zoom": 22,
  "name": "USGS Imagery",
  "transparent": false,
  "url": "https://basemap.nationalmap.gov/arcgis/services/USGSImageryOnly/MapServer/WmsServer",
  "version": "1.1.1"
 },
 "usgs topo": {
  "attribution": "USGS The National Map",
  "format": "image/png",
  "layers": "0",
  "max_zoom": 22,
  "name": "USGS Topo",
  "transparent": false,
  "url": "https://basemap.nationalmap.gov/arcgis/services/USGSTopo/MapServer/WmsServer",
  "version": "1.1.1"
 },
 "usgs topo wms": {
  "attribution": "USGS The National Map",
  "format": "image/png",
  "layers": "0",
  "max_zoom": 22,
  "name": "USGS Topo",
  "transparent": false,
  "url": "https://basemap.nationalmap.gov/arcgis/services/USGSTopo/MapServer/WmsServer",
  "version": "1.1.1"
 }
};

// What a bare map seeds, per CRS: [name, initially_visible] pairs resolved
// through addBasemap. A CRS with no row falls back to EPSG:3857's.
export const DEFAULT_BASEMAPS = {
 "EPSG:3857": [
  [
   "Open Street Map",
   true
  ],
  [
   "Dark Matter",
   false
  ]
 ],
 "EPSG:4326": [
  [
   "Esri WGS84",
   true
  ]
 ]
};

// xyzservices.query_name's tolerance: lowercase with ". -_/" removed.
export const queryKey = (name) => String(name).toLowerCase().replace(/[. \-_/]/g, "");
